# Use the latest Ubuntu base image
FROM ubuntu:latest

# Install Python 3.10, pip, and git
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install the PyYAML Python package
#RUN pip3 install PyYAML

# Copy the necessary scripts to the image
COPY feed.py /usr/bin/feed.py
COPY entrypoint.sh /entrypoint.sh

# Ensure the entrypoint script is executable
RUN chmod +x /entrypoint.sh

# Set the entrypoint to the script
ENTRYPOINT ["/entrypoint.sh"]

